name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "🚀 Features"
    labels:
      - "C-feat"
  - title: "🐛 Bug Fixes"
    labels:
      - "C-fix"
  - title: "📈 Quality"
    labels:
      - "C-perf"
      - "C-refactor"
      - "C-style"
      - "C-test"
  - title: "🧰 Maintenance"
    labels:
      - "C-build"
      - "C-chore"
      - "C-ci"
      - "C-config"
      - "C-package"
  - title: 📄 Documentation
    labels:
      - C-docs
  - title: Other Changes
    labels:
      - "*"

change-title-escapes: '\<*_&'

template: |
  ## Changes

  $CHANGES
