name: Sha
description: Show sha

inputs:
  branch:
    description: 'The branch name to notify'
    required: false

runs:
  using: composite
  steps:
    - name: Show sha
      env:
        BRANCH: ${{ inputs.branch && inputs.branch || (github.event.pull_request.merged && github.base_ref || github.head_ref) }}
      shell: bash
      run: |
        echo "Sha: ${{ env.BRANCH }}"
