name: Sha
description: Show sha

runs:
  using: composite
  steps:
    - run: |
        echo "Show github.event_name:" ${{ github.event_name }}
        echo "Show github.ref_name:" ${{ github.ref_name }}
        echo "Show github.event.pull_request.merged:" ${{ github.event.pull_request.merged }}
        echo "Show github.base_ref:" ${{ github.base_ref }}
        echo "Show github.head_ref:" ${{ github.head_ref }}
        echo "Show ref:" ${{ github.event.pull_request.merged && github.base_ref || github.head_ref }}
      shell: bash

    - name: Show sha
      env:
        BRANCH: ${{ github.event_name == 'push' && github.ref_name || (github.event.pull_request.merged && github.base_ref || github.head_ref) }}
        COMMIT_SHA: ${{ (github.event_name == 'push' || github.event.pull_request.merged) && github.sha || event.pull_request.head.sha }}
      shell: bash
      run: |
        echo "BRANCH: ${{ env.BRANCH }}"
        echo "COMMIT_SHA: ${{ env.COMMIT_SHA }}"
