name: Assign author

on:
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - name: Assign author
        uses: technote-space/assign-author@v1
