name: Assign author

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
  issues:
    types:
      - opened
      - reopened

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign
        uses: technote-space/assign-author@v1
