name: Comment Context

on:
  issue_comment:
    types: [created]

jobs:
  check-comment-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Show context
        run: |
          echo '1' ${{ github.event.issue.pull_request }}
          echo '2' ${{ github.event.comment.body }}
          echo '3' ${{ github.event.issue.pull_request.url }}
