name: Deploy

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Deploy tag (e.g. 1.2.3)"
        required: true
        type: string
      build:
        description: "Build envirinment"
        required: true
        default: stg
        type: choice
        options:
          # - dev
          - stg
          - prd
          - "prd, but not pre-release"

jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Get input tag version
        id: tag
        run: |
          tag=${{ github.event.inputs.tags }}
          if [[ $tag =~ ^v?([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            echo "version=v${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          else
            echo "Input tag ($tag) is not Semantic Versioning format. (e.g. 1.2.3)"
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: show log
        run: |
          version="${{ steps.tag.outputs.version }}"
          build="${{ github.event.inputs.build }}"

          if [[ $(git tag -l "$version" | grep -c ".") -ne 0 ]]; then
            echo "next deploy tag ($version) is already exists."
            exit 1
          fi

          if [[ $build =~ ^(stg|prd.*)$ ]]; then
            stg_num=$(expr $(git tag -l "$version-stg.[0-9]" | grep -c ".") + 1)
            echo 'next deploy tag is' "$version-stg.$stg_num"
            git tag "$version-stg.$stg_num"

            if [[ $build == 'prd' ]]; then
              rc_num=$(expr $(git tag -l "$version-rc.[0-9]" | grep -c ".") + 1)
              echo 'next deploy tag is' "$version-rc.$rc_num"
              git tag "$version-rc.$rc_num"
            else
              echo 'next deploy tag is' "$version"
              git tag "$version"
            fi

            git push origin --tags
          fi
      # - name: Tagging
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       github.rest.git.createTag({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         tag: ${{ github.event.inputs.tags }},
      #         message: ${{ github.event.inputs.tags }},
      #         object: ${{ github.sha }},
      #         type: 'commit',
      #       });
