name: Distribute app

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        type: choice
        options:
          - dev
          - stg
          - prd
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-stg.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+

jobs:
  tag-env:
    if: github.event_name == 'push' && github.event.ref_type == 'tag'
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.build.outputs.env }}
    steps:
      - name: Get build envirinment
        id: build
        run: |
          echo '1' $GITHUB_REF
          echo '2' ${{ github.ref }}
          echo '3' ${{ github.ref_name }}
          echo '4' ${{ github.head_ref }}
          echo '5' ${{ github.base_ref }}

          tag=${{ github.ref_name }}
          if [[ $tag == *"-stg"* ]]; then
              echo "env=stg" >> $GITHUB_OUTPUT
          else
              echo "env=prd" >> $GITHUB_OUTPUT
          fi

  dispatch-env:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.input.outputs.env }}
    steps:
      - name: Get input envirinment
        id: input
        run: |
          echo "env='${{ inputs.environment }}'" >> $GITHUB_OUTPUT

  show-env:
    needs:
      - tag-env
      - dispatch-env
    runs-on: ubuntu-latest
    steps:
      - name: Show env
        run: |
          echo ${{ needs.tag-env.outputs.env }}
          echo ${{ needs.dispatch-env.outputs.env }}
