name: Matrix outputs

on:
  pull_request:

jobs:
  create-env:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, prd]
        device: [android, ios]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create env json
        run: |
          prefix="${{ matrix.device }}_${{ matrix.environment }}"
          cat << EOF > ./out.json
          {
            "${prefix}_environment": "${{ matrix.environment }}",
            "${prefix}_device": "${{ matrix.device }}"
          }
          EOF

      - name: Save result to artifact
        uses: actions/upload-artifact@v4
        with:
          name: env-${{ matrix.device }}-${{ matrix.environment }}
          path: ./out.json
          overwrite: true

  get-results:
    needs: create-env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all results
        uses: actions/download-artifact@v4
        with:
          path: .

      - name: Get Results
        id: result
        run: |
          devices=("android" "ios")
          environments=("dev" "prd")

          for device in "${devices[@]}"; do
            for environment in "${environments[@]}"; do
              dir="env-${device}-${environment}"
              ls -la $dir
              file="$dir/out.json"
              if [ -f "$file" ]; then
                echo "Processing $file"
                cat $file
                jq . $file >> "$GITHUB_OUTPUT"
              else
                echo "File $file not found"
              fi
            done
          done

      - name: Show results
        run: |
          echo "${{ steps.result.outputs.ios_dev_environment }}"
          echo "${{ steps.result.outputs.ios_dev_device }}"
          echo "${{ steps.result.outputs.android_prd_environment }}"
          echo "${{ steps.result.outputs.android_prd_device }}"
