name: Pull request

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  show-context:
    runs-on: ubuntu-latest
    steps:
      - name: Show context
        run: |
          echo '1' $GITHUB_REF
          echo '2' ${{ github.ref }}
          echo '3' ${{ github.ref_name }}
          echo '4' ${{ github.head_ref }}
          echo '5' ${{ github.base_ref }}
          echo '6' ${{ github.event.pull_request.head.sha }}
          echo '7' ${{ github.sha }}
          echo '8' ${{ github.event.pull_request.merged && github.base_ref || github.head_ref }}
          echo '9' ${GITHUB_REF#refs/heads/}

  get-commit-context-0:
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.commit-message.outputs.MESSAGE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Get commit message
        id: commit-message
        run: |
          echo 'sha' ${{ github.sha }}
          echo 'head.sha' ${{ github.event.pull_request.head.sha }}
          message=$(git log --format=%B -n 1 ${{ github.event.pull_request.head.sha }})
          echo $message

  get-commit-context-1:
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.commit-message.outputs.MESSAGE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}

      - name: Get commit message
        id: commit-message
        run: |
          echo 'sha' ${{ github.sha }}
          echo 'head.sha' ${{ github.event.pull_request.head.sha }}
          message=$(git log --format=%B -n 1 ${{ github.event.pull_request.head.sha }})
          echo $message

  get-commit-context-2:
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.commit-message.outputs.MESSAGE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get commit message
        id: commit-message
        run: |
          echo 'sha' ${{ github.sha }}
          echo 'head.sha' ${{ github.event.pull_request.head.sha }}
          message=$(git log --format=%B -n 1 ${{ github.event.pull_request.head.sha }})
          echo $message
