name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-release-draft:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Update release draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yaml
          disable-autolabeler: true
