name: Revision

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0

      - run: |
          echo ${{ github.base_ref }}
          git rev-parse HEAD
