name: Show branch

on:
  pull_request:
    types: [opened, synchronize, reopened, closed, labeled]

jobs:
  check-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 2

      - name: Show ref
        run: |
          echo "github.base_ref:" ${{ github.base_ref }}
          echo "github.head_ref:" ${{ github.head_ref }}
          echo "github.ref:" ${{ github.ref }}
          echo "github.ref_name:" ${{ github.ref_name }}

  show-branch:
    runs-on: ubuntu-latest
    needs: check-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Show check
        run: |
          echo "checked:" ${{ needs.check-test.outputs.checked }}

      - name: Show context
        run: |
          echo "github.event.pull_request.merged:" ${{ github.event.pull_request.merged }}
          echo "github.event.label.name:" ${{ github.event.label.name }}
          echo "github.event.head_commit.message:" ${{ github.event.head_commit.message }}

      - name: Show branch
        uses: ./.github/actions/sha

  show-checked:
    runs-on: ubuntu-latest
    needs: check-test
    if: needs.check-test.outputs.checked
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show checked
        run: |
          echo "checked:" ${{ needs.check-test.outputs.checked }}
