name: Show branch

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  check-test:
    runs-on: ubuntu-latest
    outputs:
      checked: ${{ steps.check-message.outputs.checked }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 2

      - name: Check if the label is valid
        if: github.event.pull_request.merged == false
        id: check-message
        run: |
          message=$(git log --format=%B -n 1 ${{ github.event.pull_request.head.sha }})
          if echo "$message" | grep -F "[test]"; then
            echo "checked=true" >> "$GITHUB_OUTPUT";
          fi

  show-branch:
    runs-on: ubuntu-latest
    needs: check-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Show check
        run: |
          echo "checked:" ${{ needs.check-test.outputs.checked }}

      - name: Show context
        run: |
          echo "github.event.pull_request.merged:" ${{ github.event.pull_request.merged }}
          echo "github.event.label.name:" ${{ github.event.label.name }}
          echo "github.event.head_commit.message:" ${{ github.event.head_commit.message }}

      - name: Show branch
        uses: ./.github/actions/sha
