name: Show branch

on:
  pull_request:
    types: [opened, synchronize, reopened, closed, labeled]

jobs:
  check-test:
    runs-on: ubuntu-latest
    outputs:
      test-commit: ${{ steps.check-test.outputs.test-commit }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 2

      - name: Check test
        id: check-test
        run: |
          commit_sha=${{ github.event.pull_request.merged && github.sha || github.event.pull_request.head.sha }}
          commit_message=$(git log -1 --pretty=%s $commit_sha)
          echo "commit_message:" $commit_message
          if echo "$commit_message" | grep -q -F "[test]"; then
            echo "test-commit=true" >> "$GITHUB_OUTPUT"
          fi

  show-test:
    runs-on: ubuntu-latest
    needs: check-test
    steps:
      - name: Run test
        run: echo "needs.check-test.outputs.test-commit:" ${{ needs.check-test.outputs.test-commit }}

  test:
    runs-on: ubuntu-latest
    needs: check-test
    if: needs.check-test.outputs.test-commit
    steps:
      - name: Run test
        run: echo "Running test"
