name: Skip job

on:
  pull_request:

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check condition
        id: check-condition
        run: exit 0

      - name: Skip this job
        run: echo "This step will only run if condition is not met"
