name: Test Release

on:
  release:
    types:
      - released

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Release tag
        uses: actions/github-script@v7
        with:
          script: |
            const release_id = '${{ github.event.release.id }}'
            const tag_name = '${{ github.event.release.tag_name }}'
            const name = '${{ github.event.release.name }}'
            const version = tag_name.split('-rc.')[0];

            if (version !== tag_name) {
              github.rest.repos.updateRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: release_id,
                tag_name: version,
                name: name === tag_name ? version : name,
              });
            }
