name: WIP

on:
  pull_request:
    types:
      - opened

jobs:
  WIP:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/wip@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          labels: "do-not-merge, work in progress, wip, rfc, 🚧"
          keywords: ""
          context: WIP
          wip_description: "work in progress"
          ready_description: "ready for review"
